In [153]:
import pandas as pd

In [154]:
df_1= pd.read_csv("pib.csv")

In [155]:
df_1['Country Name']

0                                                  Aruba
1                                                    NaN
2                                             Afganistán
3                                                    NaN
4                                                 Angola
5                                                Albania
6                                                Andorra
7                                         El mundo árabe
8                                 Emiratos Árabes Unidos
9                                              Argentina
10                                               Armenia
11                                       Samoa Americana
12                                     Antigua y Barbuda
13                                             Australia
14                                               Austria
15                                            Azerbaiyán
16                                               Burundi
17                                               Bélgica
18                                                 Benin
19                                          Burkina Faso
20                                            Bangladesh
21                                              Bulgaria
22                                               Bahrein
23                                               Bahamas
24                                  Bosnia y Herzegovina
25                                               Belarús
26                                                Belice
27                                              Bermudas
28                                               Bolivia
29                                                Brasil
30                                              Barbados
31                                     Brunei Darussalam
32                                                Bhután
33                                              Botswana
34                              República Centroafricana
35                                                Canadá
36                          Europa Central y del Báltico
37                                                 Suiza
38                                       Islas del Canal
39                                                 Chile
40                                                 China
41                                         Côte d'Ivoire
42                                               Camerún
43                      Congo, República Democrática del
44                                  Congo, República del
45                                              Colombia
46                                               Comoras
47                                            Cabo Verde
48                                            Costa Rica
49                            Estados pequeos del Caribe
50                                                  Cuba
51                                               Curacao
52                                          Islas Caimán
53                                                Chipre
54                                       República Checa
55                                              Alemania
56                                              Djibouti
57                                              Dominica
58                                             Dinamarca
59                                  República Dominicana
60                                               Argelia
61     Asia oriental y el Pacífico (excluido altos in...
62                     inicial del dividendo demográfico
63                           Asia oriental y el Pacífico
64       Europa y Asia central (excluido altos ingresos)
65                                 Europa y Asia central
66                                               Ecuador
67                            Egipto, República Árabe de
68                                         Zona del Euro
69                                               Eritrea
70                                                España
71                                               Estonia
72                                               Etiopía
73                                         Unión Europea
74                                             Finlandia
75                                                  Fiji
76                                               Francia
77                                           Islas Feroe
78                     Micronesia (Estados Federados de)
79                                                 Gabón
80                                           Reino Unido
81                                               Georgia
82                                                 Ghana
83                                             Gibraltar
84                                                Guinea
85                                                Gambia
86                                         Guinea-Bissau
87                                     Guinea Ecuatorial
88                                                Grecia
89                                               Granada
90                                           Groenlandia
91                                             Guatemala
92                                                  Guam
93                                                Guyana
94                                          Ingreso alto
95             Hong Kong, Región Administrativa Especial
96                                              Honduras
97                   Países pobres muy endeudados (PPME)
98                                               Croacia
99                                                 Haití
100                                              Hungría
101                                            Sólo BIRF
102                                        BIRF y la AIF
103                                      total de la AIF
104                                     mezcla de la AIF
105                                            Indonesia
106                                             Sólo AIF
107                                          Isla de Man
108                                                India
109                                       No clasificado
110                                              Irlanda
111                         Irán, República Islámica del
112                                                 Iraq
113                                             Islandia
114                                               Israel
115                                               Italia
116                                              Jamaica
117                                             Jordania
118                                                Japón
119                                            Kazajstán
120                                                Kenya
121                                           Kirguistán
122                                              Camboya
123                                             Kiribati
124                                  Saint Kitts y Nevis
125                                  Corea, República de
126                                               Kuwait
127    América Latina y el Caribe (excluido altos ing...
128                    República Democrática Popular Lao
129                                               Líbano
130                                              Liberia
131                                                Libia
132                                          Santa Lucía
133                           América Latina y el Caribe
134    Países menos desarrollados: clasificación de l...
135                               Países de ingreso bajo
136                                        Liechtenstein
137                                            Sri Lanka
138                       Países de ingreso mediano bajo
139                               Ingreso mediano y bajo
140                                              Lesotho
141                   avanzada del dividendo demográfico
142                                             Lituania
143                                           Luxemburgo
144                                              Letonia
145       Región Administrativa Especial de Macao, China
146                  Isla de San Martín (parte francesa)
147                                            Marruecos
148                                               Mónaco
149                                 República de Moldova
150                                           Madagascar
151                                             Maldivas
152    Oriente Medio, Norte de África, Afganistán y P...
153                                               México
154                                       Islas Marshall
155                                      Ingreso mediano
156                                  Macedonia del Norte
157                                                 Malí
158                                                Malta
159                                              Myanmar
160    Oriente Medio y Norte de África (excluido alto...
161                                           Montenegro
162                                             Mongolia
163                                              Mariana
164                                           Mozambique
165                                           Mauritania
166                                             Mauricio
167                                               Malawi
168                                              Malasia
169                                    América del Norte
170                                              Namibia
171                                      Nueva Caledonia
172                                                Níger
173                                              Nigeria
174                                            Nicaragua
175                                         Países Bajos
176                                              Noruega
177                                                Nepal
178                                                Nauru
179                                       Nueva Zelandia
180                                        Miembros OCDE
181                                                 Omán
182                                Otros Estados pequeos
183                                             Pakistán
184                                               Panamá
185                                                 Perú
186                                            Filipinas
187                                                Palau
188                                   Papua Nueva Guinea
189                                              Polonia
190                      previa al dividendo demográfico
191                                     Puerto Rico (US)
192              Corea, República Popular Democrática de
193                                             Portugal
194                                             Paraguay
195                             Ribera Occidental y Gaza
196             Estados pequeos de las Islas del Pacfico
197                   posterior al dividendo demográfico
198                                   Polinesia Francesa
199                                                Qatar
200                                              Rumania
201                                  Federación de Rusia
202                                               Rwanda
203                                      Asia meridional
204                                       Arabia Saudita
205                                                Sudán
206                                              Senegal
207                                             Singapur
208                                        Islas Salomón
209                                         Sierra Leona
210                                          El Salvador
211                                           San Marino
212                         República Federal de Somalia
213                                               Serbia
214    África al sur del Sahara (excluido altos ingre...
215                                        Sudán del Sur
216                             África al sur del Sahara
217                                     Pequeños Estados
218                                Santo Tomé y Príncipe
219                                             Suriname
220                                   República Eslovaca
221                                            Eslovenia
222                                               Suecia
223                                             Eswatini
224                            Sint Maarten (Dutch part)
225                                           Seychelles
226                                República Árabe Siria
227                                Islas Turcas y Caicos
228                                                 Chad
229          Asia oriental y el Pacífico (BIRF y la AIF)
230                Europa y Asia central (BIRF y la AIF)
231                                                 Togo
232                                            Tailandia
233                                           Tayikistán
234                                         Turkmenistán
235           América Latina y el Caribe (BIRF y la AIF)
236                                          Timor-Leste
237      Oriente Medio y Norte de África (BIRF y la AIF)
238                                                Tonga
239                      Asia meridional (BIRF y la AIF)
240             África al sur del Sahara (BIRF y la AIF)
241                                    Trinidad y Tobago
242                                                Túnez
243                                              Turquía
244                                               Tuvalu
245                                             Tanzanía
246                                               Uganda
247                                              Ucrania
248                                 Ingreso mediano alto
249                                              Uruguay
250                                       Estados Unidos
251                                           Uzbekistán
252                         San Vicente y las Granadinas
253                                            Venezuela
254                            Islas Vírgenes Británicas
255                              Islas Vírgenes (EE.UU.)
256                                             Viet Nam
257                                              Vanuatu
258                                                Mundo
259                                                Samoa
260                                               Kosovo
261                                      Yemen, Rep. del
262                                            Sudáfrica
263                                               Zambia
264                                             Zimbabwe
Name: Country Name, dtype: object

In [156]:
pd.set_option('display.max_rows', None)
print(df_1['Country Name'])

0                                                  Aruba
1                                                    NaN
2                                             Afganistán
3                                                    NaN
4                                                 Angola
5                                                Albania
6                                                Andorra
7                                         El mundo árabe
8                                 Emiratos Árabes Unidos
9                                              Argentina
10                                               Armenia
11                                       Samoa Americana
12                                     Antigua y Barbuda
13                                             Australia
14                                               Austria
15                                            Azerbaiyán
16                                               Burundi
17                                               Bélgica
18                                                 Benin
19                                          Burkina Faso
20                                            Bangladesh
21                                              Bulgaria
22                                               Bahrein
23                                               Bahamas
24                                  Bosnia y Herzegovina
25                                               Belarús
26                                                Belice
27                                              Bermudas
28                                               Bolivia
29                                                Brasil
30                                              Barbados
31                                     Brunei Darussalam
32                                                Bhután
33                                              Botswana
34                              República Centroafricana
35                                                Canadá
36                          Europa Central y del Báltico
37                                                 Suiza
38                                       Islas del Canal
39                                                 Chile
40                                                 China
41                                         Côte d'Ivoire
42                                               Camerún
43                      Congo, República Democrática del
44                                  Congo, República del
45                                              Colombia
46                                               Comoras
47                                            Cabo Verde
48                                            Costa Rica
49                            Estados pequeos del Caribe
50                                                  Cuba
51                                               Curacao
52                                          Islas Caimán
53                                                Chipre
54                                       República Checa
55                                              Alemania
56                                              Djibouti
57                                              Dominica
58                                             Dinamarca
59                                  República Dominicana
60                                               Argelia
61     Asia oriental y el Pacífico (excluido altos in...
62                     inicial del dividendo demográfico
63                           Asia oriental y el Pacífico
64       Europa y Asia central (excluido altos ingresos)
65                                 Europa y Asia central
66                                               Ecuador
67                            Egipto, República Árabe de
68                                         Zona del Euro
69                                               Eritrea
70                                                España
71                                               Estonia
72                                               Etiopía
73                                         Unión Europea
74                                             Finlandia
75                                                  Fiji
76                                               Francia
77                                           Islas Feroe
78                     Micronesia (Estados Federados de)
79                                                 Gabón
80                                           Reino Unido
81                                               Georgia
82                                                 Ghana
83                                             Gibraltar
84                                                Guinea
85                                                Gambia
86                                         Guinea-Bissau
87                                     Guinea Ecuatorial
88                                                Grecia
89                                               Granada
90                                           Groenlandia
91                                             Guatemala
92                                                  Guam
93                                                Guyana
94                                          Ingreso alto
95             Hong Kong, Región Administrativa Especial
96                                              Honduras
97                   Países pobres muy endeudados (PPME)
98                                               Croacia
99                                                 Haití
100                                              Hungría
101                                            Sólo BIRF
102                                        BIRF y la AIF
103                                      total de la AIF
104                                     mezcla de la AIF
105                                            Indonesia
106                                             Sólo AIF
107                                          Isla de Man
108                                                India
109                                       No clasificado
110                                              Irlanda
111                         Irán, República Islámica del
112                                                 Iraq
113                                             Islandia
114                                               Israel
115                                               Italia
116                                              Jamaica
117                                             Jordania
118                                                Japón
119                                            Kazajstán
120                                                Kenya
121                                           Kirguistán
122                                              Camboya
123                                             Kiribati
124                                  Saint Kitts y Nevis
125                                  Corea, República de
126                                               Kuwait
127    América Latina y el Caribe (excluido altos ing...
128                    República Democrática Popular Lao
129                                               Líbano
130                                              Liberia
131                                                Libia
132                                          Santa Lucía
133                           América Latina y el Caribe
134    Países menos desarrollados: clasificación de l...
135                               Países de ingreso bajo
136                                        Liechtenstein
137                                            Sri Lanka
138                       Países de ingreso mediano bajo
139                               Ingreso mediano y bajo
140                                              Lesotho
141                   avanzada del dividendo demográfico
142                                             Lituania
143                                           Luxemburgo
144                                              Letonia
145       Región Administrativa Especial de Macao, China
146                  Isla de San Martín (parte francesa)
147                                            Marruecos
148                                               Mónaco
149                                 República de Moldova
150                                           Madagascar
151                                             Maldivas
152    Oriente Medio, Norte de África, Afganistán y P...
153                                               México
154                                       Islas Marshall
155                                      Ingreso mediano
156                                  Macedonia del Norte
157                                                 Malí
158                                                Malta
159                                              Myanmar
160    Oriente Medio y Norte de África (excluido alto...
161                                           Montenegro
162                                             Mongolia
163                                              Mariana
164                                           Mozambique
165                                           Mauritania
166                                             Mauricio
167                                               Malawi
168                                              Malasia
169                                    América del Norte
170                                              Namibia
171                                      Nueva Caledonia
172                                                Níger
173                                              Nigeria
174                                            Nicaragua
175                                         Países Bajos
176                                              Noruega
177                                                Nepal
178                                                Nauru
179                                       Nueva Zelandia
180                                        Miembros OCDE
181                                                 Omán
182                                Otros Estados pequeos
183                                             Pakistán
184                                               Panamá
185                                                 Perú
186                                            Filipinas
187                                                Palau
188                                   Papua Nueva Guinea
189                                              Polonia
190                      previa al dividendo demográfico
191                                     Puerto Rico (US)
192              Corea, República Popular Democrática de
193                                             Portugal
194                                             Paraguay
195                             Ribera Occidental y Gaza
196             Estados pequeos de las Islas del Pacfico
197                   posterior al dividendo demográfico
198                                   Polinesia Francesa
199                                                Qatar
200                                              Rumania
201                                  Federación de Rusia
202                                               Rwanda
203                                      Asia meridional
204                                       Arabia Saudita
205                                                Sudán
206                                              Senegal
207                                             Singapur
208                                        Islas Salomón
209                                         Sierra Leona
210                                          El Salvador
211                                           San Marino
212                         República Federal de Somalia
213                                               Serbia
214    África al sur del Sahara (excluido altos ingre...
215                                        Sudán del Sur
216                             África al sur del Sahara
217                                     Pequeños Estados
218                                Santo Tomé y Príncipe
219                                             Suriname
220                                   República Eslovaca
221                                            Eslovenia
222                                               Suecia
223                                             Eswatini
224                            Sint Maarten (Dutch part)
225                                           Seychelles
226                                República Árabe Siria
227                                Islas Turcas y Caicos
228                                                 Chad
229          Asia oriental y el Pacífico (BIRF y la AIF)
230                Europa y Asia central (BIRF y la AIF)
231                                                 Togo
232                                            Tailandia
233                                           Tayikistán
234                                         Turkmenistán
235           América Latina y el Caribe (BIRF y la AIF)
236                                          Timor-Leste
237      Oriente Medio y Norte de África (BIRF y la AIF)
238                                                Tonga
239                      Asia meridional (BIRF y la AIF)
240             África al sur del Sahara (BIRF y la AIF)
241                                    Trinidad y Tobago
242                                                Túnez
243                                              Turquía
244                                               Tuvalu
245                                             Tanzanía
246                                               Uganda
247                                              Ucrania
248                                 Ingreso mediano alto
249                                              Uruguay
250                                       Estados Unidos
251                                           Uzbekistán
252                         San Vicente y las Granadinas
253                                            Venezuela
254                            Islas Vírgenes Británicas
255                              Islas Vírgenes (EE.UU.)
256                                             Viet Nam
257                                              Vanuatu
258                                                Mundo
259                                                Samoa
260                                               Kosovo
261                                      Yemen, Rep. del
262                                            Sudáfrica
263                                               Zambia
264                                             Zimbabwe
Name: Country Name, dtype: object

In [157]:
paises_america = ['Antigua y Barbuda', 'Argentina', 'Bahamas', 'Barbados', 'Belice', 'Bolivia', 'Brasil', 'Canadá', 'Chile', 'Colombia', 'Costa Rica', 'Cuba', 'Dominica', 'Ecuador', 'El Salvador', 'Estados Unidos', 'Granada', 'Guatemala', 'Guyana', 'Haití', 'Honduras', 'Jamaica', 'México', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú', 'República Dominicana', 'San Vicente y las Granadinas', 'Santa Lucía', 'Suriname', 'Trinidad y Tobago', 'Uruguay', 'Venezuela']

In [158]:
df = df_1[df_1['Country Name'].isin(paises_america)]

In [159]:
df['Country Name']

9                         Argentina
12                Antigua y Barbuda
23                          Bahamas
26                           Belice
28                          Bolivia
29                           Brasil
30                         Barbados
35                           Canadá
39                            Chile
45                         Colombia
48                       Costa Rica
50                             Cuba
57                         Dominica
59             República Dominicana
66                          Ecuador
89                          Granada
91                        Guatemala
93                           Guyana
96                         Honduras
99                            Haití
116                         Jamaica
132                     Santa Lucía
153                          México
174                       Nicaragua
184                          Panamá
185                            Perú
194                        Paraguay
210                     El Salvador
219                        Suriname
241               Trinidad y Tobago
249                         Uruguay
250                  Estados Unidos
252    San Vicente y las Granadinas
253                       Venezuela
Name: Country Name, dtype: object

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 9 to 253
Data columns (total 68 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    34 non-null     int64
 1   Country Name  34 non-null     object
 2   Country Code  34 non-null     object
 3   1961          27 non-null     float64
 4   1962          27 non-null     float64
 5   1963          27 non-null     float64
 6   1964          27 non-null     float64
 7   1965          27 non-null     float64
 8   1966          28 non-null     float64
 9   1967          29 non-null     float64
 10  1968          29 non-null     float64
 11  1969          29 non-null     float64
 12  1970          29 non-null     float64
 13  1971          30 non-null     float64
 14  1972          30 non-null     float64
 15  1973          30 non-null     float64
 16  1974          30 non-null     float64
 17  1975          30 non-null     float64
 18  1976          30 non-null     float64
 19  1977          30 non-null     float64
 20  1978          34 non-null     float64
 21  1979          34 non-null     float64
 22  1980          34 non-null     float64
 23  1981          34 non-null     float64
 24  1982          34 non-null     float64
 25  1983          34 non-null     float64
 26  1984          34 non-null     float64
 27  1985          34 non-null     float64
 28  1986          34 non-null     float64
 29  1987          34 non-null     float64
 30  1988          34 non-null     float64
 31  1989          34 non-null     float64
 32  1990          34 non-null     float64
 33  1991          34 non-null     float64
 34  1992          34 non-null     float64
 35  1993          34 non-null     float64
 36  1994          34 non-null     float64
 37  1995          34 non-null     float64
 38  1996          34 non-null     float64
 39  1997          34 non-null     float64
 40  1998          34 non-null     float64
 41  1999          34 non-null     float64
 42  2000          34 non-null     float64
 43  2001          34 non-null     float64
 44  2002          34 non-null     float64
 45  2003          34 non-null     float64
 46  2004          34 non-null     float64
 47  2005          34 non-null     float64
 48  2006          34 non-null     float64
 49  2007          34 non-null     float64
 50  2008          34 non-null     float64
 51  2009          34 non-null     float64
 52  2010          34 non-null     float64
 53  2011          34 non-null     float64
 54  2012          34 non-null     float64
 55  2013          34 non-null     float64
 56  2014          34 non-null     float64
 57  2015          34 non-null     float64
 58  2016          34 non-null     float64
 59  2017          34 non-null     float64
 60  2018          34 non-null     float64
 61  2019          34 non-null     float64
 62  2020          34 non-null     float64
 63  2021          34 non-null     float64
 64  2022          34 non-null     float64
 65  2023          34 non-null     float64
 66  2024          34 non-null     float64
 67  2025          32 non-null     float64
dtypes: float64(65), int64(1), object(2)
memory usage: 18.3+ KB

In [161]:
df.head()

,Unnamed: 0,Country Name,Country Code,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
9,9,Argentina,ARG,5.427843,-0.852022,-5.308197,10.130298,10.569433,-0.659726,3.191997,...,-2.080328,2.818503,-2.617396,-2.000861,-9.900485,10.441812,6.020745,-1.855788,-1.342931,4.367333
12,12,Antigua y Barbuda,ATG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.120368,2.712727,6.712005,3.172222,-18.868777,8.172863,8.497763,3.865502,2.540442,4.998040
23,23,Bahamas,BHS,10.667097,10.451972,10.524055,10.501567,10.425596,9.071929,9.598114,...,-1.156508,3.371399,2.397955,-0.838586,-20.089366,17.586139,10.877901,3.048242,3.378666,NaN
26,26,Belice,BLZ,4.892277,4.892652,4.956434,4.999880,4.930541,4.770845,4.913123,...,-0.018741,-1.833237,0.822069,4.256587,-13.522900,17.989924,9.250513,0.500128,3.504664,2.748317
28,28,Bolivia,BOL,2.089296,5.578918,6.797626,3.956597,4.913442,7.170590,6.317220,...,4.263921,4.195206,2.868084,1.506721,-12.719469,10.029049,3.747418,2.516366,-1.123356,-1.582376

In [162]:
df.drop(columns=['Unnamed: 0'], inplace=True)

/tmp/ipykernel_1144/4136117298.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Unnamed: 0'], inplace=True)

In [163]:
df.columns

Index(['Country Name', 'Country Code', '1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024', '2025'],
      dtype='object')

In [164]:
nulos = df.isnull().sum().sort_values(ascending=False)
nulos[nulos > 0]

1961    7
1963    7
1962    7
1964    7
1965    7
1966    6
1967    5
1970    5
1969    5
1968    5
1971    4
1974    4
1975    4
1972    4
1973    4
1976    4
1977    4
2025    2
dtype: int64

In [165]:
df['Country Name'].mode()

0                Antigua y Barbuda
1                        Argentina
2                          Bahamas
3                         Barbados
4                           Belice
5                          Bolivia
6                           Brasil
7                           Canadá
8                            Chile
9                         Colombia
10                      Costa Rica
11                            Cuba
12                        Dominica
13                         Ecuador
14                     El Salvador
15                  Estados Unidos
16                         Granada
17                       Guatemala
18                          Guyana
19                           Haití
20                        Honduras
21                         Jamaica
22                          México
23                       Nicaragua
24                          Panamá
25                        Paraguay
26                            Perú
27            República Dominicana
28    San Vicente y las Granadinas
29                     Santa Lucía
30                        Suriname
31               Trinidad y Tobago
32                         Uruguay
33                       Venezuela
Name: Country Name, dtype: object

In [166]:
df[['1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024', '2025']].median()

1961    4.892277
1962    5.411890
1963    4.710291
1964    5.800000
1965    4.930541
1966    5.374420
1967    4.134864
1968    5.215142
1969    4.736909
1970    4.941887
1971    4.304692
1972    5.136571
1973    5.504995
1974    5.434903
1975    2.561628
1976    5.298744
1977    5.626284
1978    5.621016
1979    4.523075
1980    4.230209
1981    3.027257
1982   -0.095115
1983    1.223603
1984    3.083642
1985    1.959608
1986    4.057585
1987    3.492315
1988    3.605461
1989    3.507048
1990    3.327813
1991    2.242457
1992    3.545555
1993    4.088931
1994    4.031382
1995    3.878641
1996    3.874624
1997    4.593616
1998    3.892953
1999    2.710279
2000    3.705470
2001    1.680849
2002    2.494773
2003    3.729529
2004    4.602632
2005    4.129532
2006    5.240504
2007    5.263084
2008    3.413727
2009   -1.126894
2010    3.527183
2011    4.048143
2012    3.194022
2013    2.862501
2014    2.513792
2015    2.551162
2016    1.953417
2017    2.514553
2018    2.797912
2019    1.194184
2020   -8.571416
2021    8.107284
2022    4.650825
2023    2.991303
2024    2.799157
2025    2.724159
dtype: float64

In [167]:
df['Country Name'] = df['Country Name'].fillna(df['Country Name'].mode()[0])

/tmp/ipykernel_1144/991798221.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country Name'] = df['Country Name'].fillna(df['Country Name'].mode()[0])

In [168]:
df[['1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024', '2025']] = df[['1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024', '2025']].fillna(df[['1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974',
       '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983',
       '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001',
       '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010',
       '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019',
       '2020', '2021', '2022', '2023', '2024', '2025']].median())

/tmp/ipykernel_1144/247990339.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['1961', '1962', '1963', '1964', '1965',

In [169]:
nulos = df.isnull().sum().sort_values(ascending=False)
nulos[nulos > 0]

Series([], dtype: int64)